version: "3.5"

services:
  redis:
    image: bitnami/redis:7.0.15
    container_name: redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-admin123}
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb --bind "redis"
    volumes:
      - redis-data:/bitnami/redis/data
    ports:
      - '6379:6379'
    networks:
      - default

  mongodb:
    image: mongo:5.0.27
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-admin123}
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - default

  bot-api:
    image: howblox/bot-api:latest
    container_name: bot-api
    restart: unless-stopped
    environment:
      - PORT=${PORT:-44778}
      - MONGO_HOST=${MONGO_HOST:-mongodb}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-admin123}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-admin123}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - HTTP_BOT_API=http://howblox-http
      - HTTP_BOT_AUTH=${HTTP_BOT_AUTH}
      - BOT_RELEASE=${BOT_RELEASE:-LOCAL}
      - BOT_API_AUTH=${BOT_API_AUTH:-admin123}
    ports:
      - '8000:8000'
    networks:
      - default
    depends_on:
      - mongodb
      - redis

  relay-server:
    image: howblox/relay-server:latest
    container_name: relay-server
    restart: unless-stopped
    environment:
      - MONGO_HOST=${MONGO_HOST:-mongodb}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-admin123}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-admin123}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - HTTP_BOT_API=${HTTP_BOT_API}
      - HTTP_BOT_AUTH=${HTTP_BOT_AUTH:-admin123}
      - PLAYING_STATUS=${PLAYING_STATUS:-Howblox}
      - SHARD_COUNT=${SHARD_COUNT:-1}
      - SHARDS_PER_NODE=${SHARDS_PER_NODE:-1}
      - BOT_RELEASE=${BOT_RELEASE:-LOCAL}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8020}
    ports:
      - '8020:8020'
    networks:
      - default
    depends_on:
      - mongodb
      - redis

  howblox-http:
    build: .
    container_name: howblox-http
    restart: unless-stopped
    env_file: .env
    ports:
      - '8010:8010'
    networks:
      - default
    depends_on:
      - mongodb
      - redis
      - bot-api

volumes:
  redis-data:
  mongodb-data:

networks:
  default:
    name: howblox-network